server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/rungroup
spring.datasource.username=postgres
spring.datasource.password=phamdung.2301
spring.datasource.driver-class-name=org.postgresql.Driver

# Xoa bang events cu (sai schema) roi Hibernate tao lai bang moi
spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
